---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Code Coverage"
consumes:
  - application/json
produces:
  - application/json
paths:
  /coverage/file:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_for_file"
      parameters:
      - name: changeset
        in: query
        description: Changeset
        required: true
        type: string
      - name: path
        in: query
        description: File
        required: true
        type: string
      responses:
        200:
          description: Code coverage information for a given file at a given changeset
      tags:
        - legacy

  /coverage/changeset/{changeset}:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_by_changeset"
      parameters:
      - name: changeset
        in: path
        description: Changeset
        required: true
        type: string
      responses:
        200:
          description: Code coverage information by changeset
      tags:
        - legacy

  /coverage/changeset_summary/{changeset}:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_summary_by_changeset"
      parameters:
      - name: changeset
        in: path
        description: Changeset
        required: true
        type: string
      responses:
        200:
          description: Code coverage summary by changeset
      tags:
        - legacy

  /coverage/supported_extensions:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_supported_extensions"
      responses:
        200:
          description: File extensions supported for code coverage
      tags:
        - legacy

  /coverage/latest:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_latest"
      responses:
        200:
          description: Latest coverage builds
      tags:
        - legacy

  /v2/path:
    get:
      operationId: "shipit_code_coverage_backend.v2.coverage_for_path"
      parameters:
      - name: changeset
        in: query
        description: Changeset
        required: false
        type: string
      - name: path
        in: query
        description: File
        required: false
        type: string
      responses:
        200:
          description: Code coverage information for a given file or directory at a given changeset
      tags:
        - v2

  /phabricator/base_revision_from_phid/{revision_phid}:
    get:
      operationId: "shipit_code_coverage_backend.api.phabricator_base_revision_from_phid"
      parameters:
      - name: revision_phid
        in: path
        description: Revision PHID
        required: true
        type: string
      responses:
        200:
          description: hg.mozilla.org/mozilla-central base revision of the given revision
        404:
          description: No base revision has been found on hg.mozilla.org/mozilla-central
      tags:
        - legacy
